# Generated by Django 5.2.6 on 2025-09-12 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('frame_width', models.IntegerField()),
                ('frame_height', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'detections',
            },
        ),
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('prediction', models.CharField(max_length=100)),
                ('class_id', models.IntegerField()),
                ('confidence', models.FloatField()),
                ('segmentation_area_pixels', models.IntegerField()),
                ('segmentation_area_percentage', models.FloatField()),
                ('segmentation_polygons', models.JSONField()),
                ('segmentation_bounding_coordinates', models.JSONField()),
                ('segmentation_yolo_format', models.JSONField()),
                ('segmentation_size', models.JSONField()),
                ('bbox_area_pixels', models.IntegerField()),
                ('bbox_area_percentage', models.FloatField()),
                ('bbox_coordinates', models.JSONField()),
                ('bbox_yolo_format', models.JSONField()),
                ('bbox_size', models.JSONField()),
                ('segmentation_bbox_ratio', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='ai.detection')),
            ],
            options={
                'db_table': 'detected_objects',
            },
        ),
        migrations.CreateModel(
            name='DetectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'detection_sessions',
            },
        ),
        migrations.AddField(
            model_name='detection',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='ai.detectionsession'),
        ),
    ]
