# Generated by Django 5.2.6 on 2025-09-12 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedobject',
            name='detection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_objects', to='ai.detection'),
        ),
    ]
