# Generated by Django 5.2.6 on 2025-09-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_detectedobject_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedobject',
            name='detection_type',
            field=models.CharField(choices=[('segmentation', 'Segmentation'), ('detection', 'Object Detection')], default='segmentation', max_length=20),
        ),
        migrations.AlterField(
            model_name='detectedobject',
            name='segmentation_area_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detectedobject',
            name='segmentation_area_pixels',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detectedobject',
            name='segmentation_bbox_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detectedobject',
            name='segmentation_bounding_coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detectedobject',
            name='segmentation_polygons',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detectedobject',
            name='segmentation_size',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detectedobject',
            name='segmentation_yolo_format',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
